[source]
name='pencil'
nphotons=100000
position=[0.0, 0.0, 9.999]
direction=[0.0, 0.0, -1.0]

[grid]
nxg=200
nyg=200
nzg=200
xmax=10.0
ymax=10.0
zmax=10.0

[geometry]
geom_name='raman_test'

[[detectors]]
type="annulus"
position=[0.1, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.2, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.3, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.4, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.5, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.6, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.7, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.8, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[0.9, 0.0, 0.0]
radius1=0.25
radius2=0.5

[[detectors]]
type="annulus"
position=[1.0, 0.0, 0.0]
radius1=0.25
radius2=0.5

[output]
fluence='raman.nrrd'
render="raman.nrrd"
render_geom=false
overwrite=true

[simulation]
iseed=123456789
tev=false

