[source]
name = "point"
nphotons = 100000
position = [0.0, 0.0, 0.0]
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "scat_test"
tau = 10.0

[output]
fluence = "fluence.nrrd"
render = "geom_render.nrrd"
render_geom = false
overwrite = true

[simulation]
iseed = 123456789
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000